version: "3"

networks:
  network1:
    driver: bridge

services:
  log:
    container_name: ev3_elk
    build: ./misc/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "7777:7777/udp"
    networks:
      - network1

  haproxy:
    container_name: proxy
    ports:
      - "6000:6000"
    build: ./haproxy
    depends_on:
      - users_api
      - posts_api
    networks:
      - network1

  users_api:
    container_name: users_api
    build: ./users_api
    ports:
      - "4000:4000"
    depends_on:
      - log
    environment:
      - MONGO_URI=${MONGO_URI}
      - TOKEN_KEY=${TOKEN_KEY}
      - LOGSTASH=${LOGSTASH}
    networks:
      - network1

  posts_api:
    container_name: posts_api
    build: ./posts_api
    ports:
      - "3001:3001"
    depends_on:
      - log
      - redis
    environment:
      - MONGO_URI=${MONGO_URI}
      - TOKEN_KEY=${TOKEN_KEY}
      - LOGSTASH=${LOGSTASH}
    networks:
      - network1

  redis:
    container_name: ev3_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - network1
